#!/bin/sh

CACHE_LOCATION="/mnt/cache"
UNION_LOCATION="/mnt/union"

# This is inelegant, but I don't care
umount "$UNION_LOCATION"/tmp
umount "$UNION_LOCATION"/proc
umount "$UNION_LOCATION"/sys
umount "$UNION_LOCATION"/dev/shm
umount "$UNION_LOCATION"/dev/pts
umount "$UNION_LOCATION"/dev
umount "$UNION_LOCATION"/

umount "$CACHE_LOCATION"
